# v2 syntax
version: '2'

# Named volumes
volumes:
  # MySQL Data
  freshII-mysql-data:
    driver: local

  # Redis Data
  freshII-redis-data:
    driver: local

services:
  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: freshII-mysql
    volumes:
      - freshII-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=freshII
      - MYSQL_DATABASE=freshII
      - MYSQL_USER=freshII
      - MYSQL_PASSWORD=freshII

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: freshII-redis
    command: --appendonly yes
    volumes:
      - freshII-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Nginx)
  app:
    image: ambientum/php:7.1-nginx
    container_name: freshII-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: freshII-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache